# This file has been generated by mvnix 0.1.0. Configure the build here!
{
  fetchFromGitHub ? (import <nixpkgs> {}).fetchFromGitHub,
  pkgs ? import (fetchFromGitHub {
    owner   = "NixOS";
    repo    = "nixpkgs";
    rev     = "18.09";
    sha256  = "1ib96has10v5nr6bzf7v8kw7yzww8zanxgw2qi1ll1sbv6kj6zpd";
  }) {},
  nix-git-ignore-source ? import (fetchFromGitHub {
    owner = "icetan";
    repo  = "nix-git-ignore-source";
    rev = "8dbacb16c6727ed71d9ed82b6d54a66aa921859f";
    sha256 = "1afyzm700y2j3fv3m764gpwpxqd3bh2xsi4dfqnfcrw2n6x03aym";
  }) { inherit pkgs; },
  mavenix ? pkgs.callPackage (import ./mavenix.nix) { },
  doCheck ? false,
}: with pkgs;

mavenix {
  inherit doCheck;

  src         = nix-git-ignore-source.gitIgnoreSource ../.;
  name        = "k";
  infoFile    = ./mavenix-info.json;
  buildInputs = [ git makeWrapper ];

  MAVEN_OPTS = "-DskipKTest=true -Dllvm.backend.skip=true";

  remotes = {
    "central" = "https://repo.maven.apache.org/maven2";
    "runtime.verification" = "https://s3.us-east-2.amazonaws.com/runtimeverificationmaven/internal";
    "runtime.verification.snapshots" = "https://s3.us-east-2.amazonaws.com/runtimeverificationmaven/snapshots";
  };

  postInstall = ''
    cp -r k-distribution/target/release/k/{bin,include,lib} $out/

    for prog in $out/bin/*; do
      wrapProgram $prog \
        --prefix PATH : ${lib.makeBinPath [
          openjdk8 flex z3 gmp mpfr pkgconfig python3 opam ocaml ocamlPackages.findlib
        ]}
    done
  '';
}
